"""Generated by bootstrap_github_project.py; do not edit manually."""

PROJECT_NUMBER = "4"
PROJECT_OWNER = "@me"
PROJECT_ID = "PVT_kwHOApeba84Bhf2x"
PRIORITY_FIELD_ID = "PVTSSF_lAHOApeba84Bhf2xzhgbY60"
PRIORITY_OPTION_IDS = {"high": "52e70f3f", "medium": "a48fdb74", "low": "28ce4089"}
STATUS_FIELD_ID = "PVTSSF_lAHOApeba84Bhf2xzhgbY64"
STATUS_OPTION_IDS = {"planned": "aec55350", "in-progress": "fdfac3be"}


def require_configured() -> None:
    return None
